### ISSUE TITLE
Repository is down

### ISSUE THREAD

**Issue by akvyalkov** [LateralThoughts/mongo-java-driver-stub#1]
Repository is returning 503 error.
Link I'm using: http://nexus.lateral-thoughts.com/content/repositories/lateral-releases/org/mongodb/mongo-java-driver-stub/0.13/mongo-java-driver-stub-0.13.pom

**Comment by fbiville** [comment]
http://nexus.lateral-thoughts.com/ is down

**Comment by jblemee** [comment]
This repository is no longer maintained, please use Fongo : https://github.com/foursquare/fongo
